In [1]:
import sys
from pathlib import Path

#Ensure project root is available for imports
PROJECT_ROOT = Path("..").resolve()
sys.path.append(str(PROJECT_ROOT))

In [28]:
#Imports
import numpy as np

#Import functions from .py files
from src.data_loader import load_data
from src.feature_engineering import add_engineered_features
from src.inference import predict_from_xml 

from sklearn.metrics import mean_absolute_error, mean_squared_error

#load data
#Database path
db_path = r"C:\Users\jacov\anaconda_projects\Marvel Insurance\data\superhero_events_db.duckdb"

df = load_data(db_path)
df = add_engineered_features(df)

print("Dataset shape:", df.shape)
df.head(25)

Warning: Malformed XML detected.
Dataset shape: (91, 11)

,index,name,CreditInfo,annual_public_destruction_events,credit_score,age,num_superpowers,num_properties,num_credit_cards,total_credit_limit,xml_parse_error
0,0,Nyx,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",23,436.0,47.0,3,6,1,1117,0
1,1,Nova,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",24,215.0,29.0,3,2,4,154863,0
2,2,Psylocke,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",18,344.0,62.0,2,1,4,109612,0
3,3,Cerberus,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",8,460.0,76.0,2,0,0,0,0
4,4,Iron Man,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",12,475.0,77.0,3,0,2,166017,0
5,5,Professor X,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",21,567.0,70.0,4,11,4,118737,0
6,6,Magneto,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",28,167.0,36.0,4,8,0,0,0
7,7,Frigg,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",31,565.0,20.0,4,9,2,78137,0
8,8,Eros,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",28,81.0,54.0,2,13,1,77325,0
9,9,Wolverine,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",10,477.0,81.0,2,3,1,54173,0
10,10,Eitri,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",30,270.0,49.0,4,9,1,98945,0
11,11,Freya,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",31,53.0,42.0,2,14,3,129712,0
12,12,Icarus,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",20,493.0,59.0,1,11,0,0,0
13,13,Groot,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",17,521.0,42.0,1,8,2,24182,0
14,14,Jason,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",16,593.0,26.0,3,2,4,218715,0
15,15,Doctor Strange,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",23,231.0,76.0,1,9,0,0,0
16,16,Odin,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",30,33.0,66.0,3,7,2,54848,0
17,17,Deadpool,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",22,739.0,55.0,3,2,1,12555,0
18,18,Chaos,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",21,398.0,57.0,3,6,3,124778,0
19,19,Skurge,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",18,691.0,81.0,4,12,4,121655,0
20,20,Black Panther,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",23,231.0,63.0,3,6,4,104606,0
21,21,Fenrir,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",37,699.0,69.0,2,6,1,36435,0
22,22,X-23,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",18,574.0,75.0,1,12,3,222392,0
23,23,Vision,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",15,556.0,38.0,2,11,3,140588,0
24,24,Gamora,"<?xml version=""1.0"" encoding=""UTF-8"" ?><superh...",24,231.0,80.0,1,8,0,0,0

In [3]:
#List of all new applicatant - predicted

#Superheroes without known destruction events
to_predict = df[df["annual_public_destruction_events"].isnull()]

print("Number of new applicants:", len(to_predict))
print("\nSuperheroes to predict for:")
print(to_predict["name"].tolist())

Number of new applicants: 21

Superheroes to predict for:
['Elektra', 'Juggernaut', 'Ant-Man', 'Thanos', 'Bucky Barnes', 'X-Men', 'Xena', 'Mimir', 'Rocket Raccoon', 'Jormungandr', 'Scarlet Witch', 'Zephyrus', 'Lorelei', 'Zeus', 'Nick Fury', 'Balder', 'Ororo Munroe', 'Idunn', 'Baldur', 'Thor', 'Daredevil']

In [30]:
#Test 2 non-client superheroes
heroes_to_test = ["Ant-Man", "Scarlet Witch"]

for hero in heroes_to_test:
    try: 
        sample_xml = df.loc[df["name"] == hero, "CreditInfo"].iloc[0]
        prediction = predict_from_xml(sample_xml) #Note that the prediction function round up.
        print(f"{hero}: Predicted destruction events = {prediction: .2f}")
    except Exception as e:
        print(f"{hero}: Error -> {e}")

Ant-Man: Predicted destruction events =  29.00
Scarlet Witch: Predicted destruction events =  20.00

In [18]:
#Predictions for new applicants

#Remove malformed XML if present
if "xml_parse_error" in to_predict.columns: to_predict = to_predict[to_predict["xml_parse_error"] == 0]

#Generate predictions
to_predict["predicted_destruction"] = to_predict["CreditInfo"].apply(lambda xml: predict_from_xml(xml))

#Clean table
underwriting_table = to_predict[["name", "predicted_destruction", "credit_score", "age", "num_properties"]].sort_values("name", ascending=True)

print("Prediction on new clients")
underwriting_table.head(22)

Prediction on new clients

              name  predicted_destruction  credit_score   age  num_properties
72         Ant-Man                     29         268.0  21.0               4
85          Balder                     23         469.0  54.0               8
88          Baldur                     27         230.0  25.0              12
74    Bucky Barnes                     20         499.0  68.0              12
90       Daredevil                     26         339.0  26.0               5
70         Elektra                     18         325.0  63.0               0
87           Idunn                     20         658.0  65.0              10
79     Jormungandr                     17         548.0  36.0               2
71      Juggernaut                     19         690.0  53.0               7
82         Lorelei                     15         396.0  79.0               3
77           Mimir                     22         420.0  43.0               7
84       Nick Fury                     26         144.0  71.0              14
86    Ororo Munroe                     29          42.0  76.0               4
78  Rocket Raccoon                     19         394.0  55.0               3
80   Scarlet Witch                     20         695.0  31.0               0
73          Thanos                     20         556.0  47.0              10
89            Thor                     17         634.0  20.0               1
75           X-Men                     19         602.0  80.0               9
76            Xena                     20         501.0  68.0               9
81        Zephyrus                     21          62.0  38.0               0
83            Zeus                     23         455.0  46.0               8